ROUTES = [
    {
        "Route No.": 1,
        "Route Name": "Nagole 'x' Roads to VCE",
        "Boarding Points": [
            "Nagole Metro",
            "Ramanthapur Modern Bakery",
            "D-Mart",
            "HPS",
            "T.V.Studio",
            "Amberpet 'x' Roads",
            "6 No.",
            "Shivam Road",
            "Vidyanagar 'x' Roads",
            "VST",
            "RTC 'x' Roads",
            "Indira Park",
            "Telugutalli Flyover",
            "Lakdikapool",
            "Mehdipatnam",
            "VCE"
        ],
        "Starting Time (Morning)": "7:55 AM",
        "Departure Time (Evening)": "4:35 PM",
    },
    {
        "Route No.": 2,
        "Route Name": "Uppal Depot. to VCE",
        "Boarding Points": [
            "Peerzadigua Kaman",
            "Uppal Bus Stop",
            "Uppal 'x' Roads",
            "Survey of India",
            "Street No.8 Main Road",
            "Habsiguda 'x' Roads",
            "Tarnaka",
            "Adikmet",
            "Vidyanagar",
            "Shankermutt",
            "Nallakunta Fever Hospital",
            "Barkathpura 'x' Roads",
            "Narayanguda",
            "Himayathnagar",
            "Liberty",
            "Lakdikapool",
            "Mehdipatnam",
            "VCE"
        ],
        "Starting Time (Morning)": "7:55 AM",
        "Departure Time (Evening)": "4:35 PM"
    },
    {
        "Route No.": 3,
        "Route Name": "ECIL 'x' Roads - VCE",
        "Boarding Points": [
            "Kushaiguda D-Mart",
            "ECIL",
            "Radhika Theatre",
            "A.S.Rao Nagar",
            "Naredmet 'x' Roads",
            "Vinayak Nagar",
            "Krupa Complex",
            "Safilguda",
            "Anandbagh",
            "Vani Nagar",
            "Anu Tex",
            "Malkajigiri",
            "Mirzalguda",
            "Lalaguda",
            "Mettiguda",
            "Allagadda",
            "Chilkalguda 'x' Roads",
            "Boiguda 'x' Roads",
            "Musheerabad 'x' Roads",
            "Kawadiguda",
            "Lower Tankbund",
            "Lakdikapool",
            "Mehdipatnam",
            "VCE"
        ],
        "Starting Time (Morning)": "7:55 AM",
        "Departure Time (Evening)": "4:35 PM"
    },
    {
        "Route No.": 4,
        "Route Name": "Moula - Ali - VCE",
        "Boarding Points": [
            "Coca Cola",
            "Housing Board",
            "1st Phase",
            "Noma Function Hall",
            "Mallapur",
            "Nacharam",
            "Delhi Public School",
            "HMT Bus Stop",
            "Habsiguda 'x' Roads",
            "Tarnaka",
            "Adikmet",
            "Vidyanagar",
            "Shankermutt",
            "Nallakunta Fever Hospital",
            "Barkathpura 'x' Roads",
            "Narayanguda",
            "Himayathnagar",
            "Liberty",
            "Lakdikapool",
            "Mehdipatnam",
            "VCE"
        ],
        "Starting Time (Morning)": "7:55 AM",
        "Departure Time (Evening)": "4:35 PM"
    },
    {
        "Route No.": 5,
        "Route Name": "PATANCHERU - VCE",
        "Boarding Points": [
            "Bheeramguda",
            "R.C. Puram",
            "Ashok Nagar",
            "Lingampally 'x' Roads",
            "Nallagandla Rythu Bazar",
            "Seri Lingampally",
            "HCU Bus Depot",
            "Gachibowli",
            "ORR",
            "VCE"
        ],
        "Starting Time (Morning)": "8:15 AM",
        "Departure Time (Evening)": "4:35 PM"
    },
    {
        "Route No.": 6,
        "Route Name": "ALWAL (Indira Gandhi Statue) - VCE",
        "Boarding Points": [
            "Alwal Main Road",
            "Lothukunta",
            "Lal Bazar",
            "Tirumalagiri",
            "Kharkhana",
            "JBS",
            "Patny",
            "Paradise"
        ],
        "Starting Time (Morning)": "7:55 AM",
        "Departure Time (Evening)": "4:35 PM"
    },
    {
        "Route No.": 7,
        "Route Name": "BHEERAMGUDA - VCE",
        "Boarding Points": [
            "Ashoknagar",
            "Lingampally 'x' Roads",
            "Chandanagar",
            "Gangaram",
            "Madinaguda",
            "Alwyn 'x' Roads",
            "Hafeezpet",
            "Kondapur",
            "Kothaguda 'x' Roads",
            "Gachibowli",
            "Outer Ring Road",
            "Narsingi",
            "VCE"
        ],
        "Starting Time (Morning)": "8:10 AM",
        "Departure Time (Evening)": "4:35 PM"
    },
    {
        "Route No.": 8,
        "Route Name": "Mehdipatnam - VCE",
        "Boarding Points": [
            "Humayun Nagar P.S.",
            "Mehdipatnam",
            "Rethibowli",
            "Pillar No.68",
            "VCE"
        ],
        "Starting Time (Morning)": "8:55 AM",
        "Departure Time (Evening)": "4:35 PM"
    }
]